repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=2000'] # <-- 2000KB（2MB）まで許可
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: debug-statements
      - id: check-docstring-first

  # Backend API Service (Node.js/TypeScript)
  - repo: local
    hooks:
      - id: eslint-api
        name: ESLint (API Service)
        entry: powershell -Command "cd backend/api_service; npm run lint"
        language: system
        files: ^backend/api_service/.*\.(ts|tsx|js|jsx)$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^backend/api_service/
        types: [file]
        types_or: [javascript, jsx, ts, tsx, json, css, scss, html, yaml, markdown]

  # Frontend (Next.js/React/TypeScript)
  - repo: local
    hooks:
      - id: eslint-frontend
        name: ESLint (Frontend)
        entry: powershell -Command "cd frontend; npm run lint"
        language: system
        files: ^frontend/.*\.(ts|tsx|js|jsx)$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^frontend/
        types: [file]
        types_or: [javascript, jsx, ts, tsx, json, css, scss, html, yaml, markdown]

  # Backend Document Generation Service (Python)
  - repo: local
    hooks:
      - id: black-docgen
        name: Black (Document Generation Service)
        entry: powershell -Command "cd backend/docgen_service; pipenv run black ."
        language: system
        files: ^backend/docgen_service/.*\.py$

      - id: flake8-docgen
        name: Flake8 (Document Generation Service)
        entry: powershell -Command "cd backend/docgen_service; pipenv run flake8 ."
        language: system
        files: ^backend/docgen_service/.*\.py$

      - id: mypy-docgen
        name: MyPy (Document Generation Service)
        entry: powershell -Command "cd backend/docgen_service; pipenv run mypy ."
        language: system
        files: ^backend/docgen_service/.*\.py$
